DEVICE_PATH := device/zyb/tb8786p1_64_k510_wifi

ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true

TARGET_BOARD_PLATFORM := mt6768
BOARD_HAS_MTK_HARDWARE := true
MTK_PLATFORM := mt6768
TARGET_CPU_SMP := true
BOARD_HAS_NO_BLUETOOTH := true
BOARD_HAS_NO_MOBILE_DATA := true

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a73
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_VARIANT := cortex-a53

TARGET_BOOTLOADER_BOARD_NAME := tb8786p1_64_k510_wifi
TARGET_NO_BOOTLOADER := true
BOARD_BOOTLOADER_HEADER_VERSION := 4

# AB分区配置（保留你的设置）
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS := boot vendor_boot dtbo vbmeta vbmeta_system vbmeta_vendor init_boot super
BOARD_USES_VIRTUAL_AB := false
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_FLASH_BLOCK_SIZE := 4096
TARGET_USES_MKE2FS := true

# 分区大小配置
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x2000000
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x37C6CF8000
BOARD_SUPER_PARTITION_SIZE := 0x280000000
BOARD_METADATAIMAGE_PARTITION_SIZE := 0x2000000
BOARD_DTBOIMG_PARTITION_SIZE := 0x800000
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 0x800000
BOARD_VBMETAIMAGE_PARTITION_SIZE := 0x800000
BOARD_TEEIMAGE_PARTITION_SIZE := 0x600000
BOARD_LOGOIMAGE_PARTITION_SIZE := 0x900000

BOARD_SUPER_PARTITION_GROUPS := zyb_dynamic_partitions
BOARD_ZYB_DYNAMIC_PARTITIONS_SIZE := 0x280000000
BOARD_ZYB_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product system_ext
BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true

# 明确预编译内核路径，避免冲突
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz-dtb
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/dtb/mt6768.dtb
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
# 新增：指定内核目标，避免命令冲突
TARGET_KERNEL_CONFIG := tb8786p1_64_k510_wifi_defconfig
TARGET_KERNEL_SOURCE := $(DEVICE_PATH)/prebuilt
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=user androidboot.selinux=permissive
BOARD_MKBOOTIMG_ARGS := \
    --header_version 4 \
    --kernel_offset 0x00008000 \
    --ramdisk_offset 0x11000000 \
    --tags_offset 0x13f00000 \
    --dtb $(TARGET_PREBUILT_DTB) \
    --kernel $(TARGET_PREBUILT_KERNEL)

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext

TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_SUPPORTS_FLASH_FROM_STORAGE := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_SELECT_BUTTON := true

# TWRP配置
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := zh_CN
TW_SCREEN_WIDTH := 1200
TW_SCREEN_HEIGHT := 1920
TW_ROTATE_SCREEN := false
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 150
TW_MTK := true
TW_NO_REBOOT_BOOTLOADER := false
TW_INCLUDE_NV_DATA_BACKUP := true
TW_EXCLUDE_CELLULAR := true
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
# 彻底禁用splash（解决缺失警告）
TW_SPLASH_PATH := none
TW_SKIP_SPLASH_IMAGE := true
TW_DISABLE_SPLASH := true
TW_NO_SPLASH := true
# 新增：强制生成vendor_boot
TW_BUILD_VENDOR_BOOT := true

# 其他配置
PLATFORM_SECURITY_PATCH := 2024-09-05
VENDOR_SECURITY_PATCH := 2024-09-05
PLATFORM_VERSION := 12.0.0
TARGET_BOOT_DEVICE := tb8786p1_64_k510_wifi

BOARD_AVB_ENABLE := false
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2

BOARD_SEPOLICY_DIRS := \
    $(DEVICE_PATH)/sepolicy \
    device/mediatek/sepolicy
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS := $(DEVICE_PATH)/sepolicy/public
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS := $(DEVICE_PATH)/sepolicy/private

PRODUCT_PROPERTY_OVERRIDES ?=

TARGET_SCREEN_WIDTH := $(TW_SCREEN_WIDTH)
TARGET_SCREEN_HEIGHT := $(TW_SCREEN_HEIGHT)

TW_INCLUDE_RECOVERY_DTBO := true
BOARD_INCLUDE_DTB_IN_RECOVERY_IMAGE := true

BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x4000000
BOARD_RECOVERYIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_RECOVERY_DEVICE := tb8786p1_64_k510_wifi

# 补充tee/logo分区适配
BOARD_HAS_TEE := true
BOARD_HAS_LOGO := true