TW_DEVICE_VERSION := 3.7.0-zyb
TW_DEVICE_MANUFACTURER := ZYB
TW_DEVICE_MODEL := ZPD1321
TW_DEVICE_FULL_NAME := tb8786p1_64_k510_wifi

TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_INTERNAL_STORAGE_PATH := "/data/media/0"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"

TW_SPLASH_PATH := none
TW_SKIP_SPLASH_IMAGE := true

TW_DISABLE_PRODUCT_VAR_ASSIGN := true

TW_MTK := true
TW_MTK_DEVICE := true
TW_INCLUDE_MTK_APDB := true

PRODUCT_PROPERTY_OVERRIDES += \
    ro.twrp.version=3.7.0-zyb \
    ro.twrp.build.date=$(shell date +%Y%m%d)