# tb8786p1_64_k510_wifi TWRP ◊® Ù≈‰÷√
TW_DEVICE_VERSION := 3.7.0-zyb
TW_DEVICE_MANUFACTURER := ZYB
TW_DEVICE_MODEL := ZPD1321
TW_DEVICE_FULL_NAME := tb8786p1_64_k510_wifi
# ∆Ω∞Â¥Ê¥¢¬∑æ∂  ≈‰
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_INTERNAL_STORAGE_PATH := "/data/media/0"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"